import { Metadata } from "next";
import Link from "next/link"

export const metadata: Metadata = {
  title: "Portfólio - Sobre",
  description: "Generated by create next app",
};


export default function Sobre(){
    return(
        <>
            <div className=" grid text-black justify-center-safe  mr-200 px-8 py-8 ">
                <h1 className="text-[50px] text-shadow-lg/20 animate-pulse lg:text-5xl font-bold ">Sobre mim.</h1>
                </div>
        </>
    )
}