import type { Metadata } from "next";
import "./globals.css";
import Header from "./componets/header/header";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Portfólio Jamesson Lucas",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${montserrat.variable} antialiased min-h-screen`}>
        <div className="flex items-center justify-center font-montserrat w-screen h-14 bg-black "><Header /></div>
        {children}
      </body>
    </html>
  );
}

