import type { Metadata } from "next";
import "./globals.css";
import Header from "./componets/header/header";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Portfólio Jamesson Lucas",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <div className="flex items-center justify-center bg-zinc-50 font-sans dark:bg-black"><Header /></div>
        {children}
      </body>
    </html>
  );
}

