import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Portfólio - Contato",
  description: "Generated by create next app",
};


export default function Contato(){
    return(
        <>
            <div>
                <h1 className="text-black">Page Contato</h1>
            </div>
        </>
    )
}