import Image from 'next/image';
import { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Portfólio - Projetos',
  description: 'Generated by create next app',
};

export default function Projetos() {
  return (
    <>
      <div className="grid w-full pt-[76px] md:px-20 max-w-[1080px] mx-auto">
        <h1 className="text-5xl md:justify-self-start justify-self-center md:text-5xl font-bold text-white">
          Projetos
        </h1>
      </div>

      <div className="grid md:grid-cols-3 gap-8 px-20 md:px-6 justify-center max-w-[1080px] py-10 mx-auto">
        {/* CARD */}
        <div className="bg-[#F2B47B] rounded-3xl hover:scale-105 transition duration-300 ">
          {/* IMAGEM */}
          <Link href={`https://portfoliojamessonlucas.vercel.app/`}>
            <div className="bg-white rounded-2xl shadow-xl rounded-b-none overflow-hidden ">
              <Image
                src="/preview-porfolio.png"
                alt="Projeto"
                width={1920}
                height={1080}
                className="w-full h-auto object-cover hover:scale-104 transition duration-300 cursor-pointer"
              />
            </div>
          </Link>
          {/* TEXTO */}
          <div className="mt-2 px-4 text-left text-white">
            <p className="text-sm text-center leading-tight">
              Projeto voltado ao meu portfólio para mostrar minhas habilidades
              utilizando as ferramentas Next.js, React, Typescript e
              Tailwind.css.
            </p>
          </div>
          <div className="grid grid-cols-2 justify-self-center gap-4 pt-4 pb-4">
            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/nextjs-icon.png"
              alt="next"
              width={42}
              height={70}
            ></Image>

            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/react-logo.png"
              alt="logo-react"
              width={42}
              height={70}
            ></Image>

            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/typescript.png"
              alt="typescript"
              width={42}
              height={70}
            ></Image>

            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/tailwindcss.png"
              alt="tailwdind"
              width={42}
              height={70}
            ></Image>
          </div>
        </div>

        <div className="bg-[#F2B47B] rounded-3xl overflow-hidden hover:scale-104 transition duration-300">
          <div className="bg-black shadow-xl rounded-b-none overflow-hidden aspect-video">
            <Image
                src="/projeto-calc.png"
                alt="Projeto"
                width={1920}
                height={1080}
                className="w-full h-auto object-cover object-center hover:scale-104 transition duration-300 cursor-pointer"
              />
          </div>
          <div className="mt-2 px-4 text-left text-white">
            <p className="text-sm text-center leading-tight">
              Projeto de uma calculadora com os conceitos básicos dela,
              feita com as ferramentas Html5, Css3 e JavaScript.
            </p>
          </div>
          <div className="grid grid-cols-2 justify-self-center gap-4 pt-4 pb-4">
            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/html-icon.png"
              alt="html"
              width={42}
              height={70}
            ></Image>
            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/css-icon.png"
              alt="css"
              width={42}
              height={70}
            ></Image>
            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/javascript-icon.png"
              alt="js"
              width={42}
              height={70}
            ></Image>
          </div>
        </div>

        <div className="bg-[#F2B47B] rounded-3xl hover:scale-105 transition duration-300">
          <div className="bg-white rounded-2xl shadow-xl rounded-b-none overflow-hidden">
            <Image
                src="/preview-porfolio.png"
                alt="Projeto"
                width={1920}
                height={1080}
                className="w-full h-auto object-cover hover:scale-104 transition duration-300 cursor-pointer"
              />
          </div>
          <div className="mt-2 px-4 text-left text-white">
            <p className="text-sm text-center leading-tight">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry's
            </p>
          </div>

          <div className="flex justify-center gap-4 pb-4 px-6 pt-18 ">
            <Image
              className="cursor-pointer inset-shadow-sm inset-shadow-white hover:shadow-2xl/100 hover:bg-white transition duration-300 rounded-xl p-[4px] w-auto h-auto"
              src="/react-logo.png"
              alt="logo-react"
              width={42}
              height={70}
            ></Image>
          </div>
        </div>
      </div>
    </>
  );
}
