import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Portfólio - Projetos",
  description: "Generated by create next app",
};


export default function Projetos(){
    return(
        <>
            <div className="text-black">
                <h1>Pag Projetos</h1>
            </div>
        </>
    )
}